FROM node:lts-buster
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN apt-get update
RUN apt-get install mesa-opencl-icd -y
RUN apt-get install ocl-icd-opencl-dev -y
RUN apt-get install gcc -y
RUN apt-get install git -y
RUN apt-get install bzr -y
RUN apt-get install jq  -y
RUN apt-get install pkg-config  -y
RUN apt-get install curl  -y
RUN apt-get install clang  -y
RUN apt-get install build-essential  -y
RUN apt-get install hwloc  -y
RUN apt-get install libhwloc-dev  -y
RUN apt-get install wget -y
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y | sh
RUN wget -c https://golang.org/dl/go1.16.4.linux-amd64.tar.gz -O - | tar -xz -C /usr/local
ENV PATH="/usr/local/go/bin:${PATH}"
RUN git clone https://github.com/filecoin-project/lotus.git
COPY startLotus.sh startLotus.sh
RUN mkdir lotusDevnet
RUN mkdir lotusminerDevnet

WORKDIR /lotus
RUN make 2k

ENV LOTUS_SKIP_GENESIS_CHECK=_yes_
ENV LOTUS_PATH=/lotusDevnet
ENV LOTUS_MINER_PATH=/lotusminerDevnet

ADD startLotus.sh /usr/local/bin/startLotus.sh
RUN chmod 777 /usr/local/bin/startLotus.sh

CMD /usr/local/bin/startLotus.sh
ENTRYPOINT /bin/bash

# RUN chown -R node /usr/src/app


# ENV NODE_ENV=production
# COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
# RUN npm install --production --silent && mv node_modules ../
# COPY . .
# EXPOSE 3000
# USER node
# CMD ["npm", "start"]
